# Generated by Django 2.0.5 on 2020-05-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20200528_1452'),
        ('shops', '0007_auto_20200528_1505'),
    ]

    operations = [
    ]
