# Generated by Django 2.0.5 on 2020-05-28 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0008_merge_20200528_1523'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
    ]
